name: Rust

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            feature: vulkan
            artifact_prefix: linux
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            feature: vulkan
            artifact_prefix: windows
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            feature: metal
            artifact_prefix: macos
            target: x86_64-apple-darwin
    steps:
    - name: Installing Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Installing Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get update
          sudo apt-get install -y -qq gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev 
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --features "${{ matrix.feature }}" --target ${{ matrix.target }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ matrix.os }}
        path: target/debug/${{ matrix.artifact_prefix }}
